import React, { useState } from 'react';
import { useDocuments } from '../context/DocumentContext';
import { exportToExcel, exportToCSV, exportToJSON, exportToPDF, exportToTXT } from '../utils/exportUtils';
import {
  Download,
  FileSpreadsheet,
  FileText,
  Code,
  FileCheck,
  CheckCircle2,
  AlertTriangle,
  Copy,
  Check,
  Sparkles,
  ShieldCheck,
  Database
} from 'lucide-react';

export const ExportPage = () => {
  const {
    documents,
    applicantName,
    totalDocuments,
    totalFields,
    verifiedFields,
    needsReviewFields,
    averageConfidence,
    addToast
  } = useDocuments();

  const [copiedCode, setCopiedCode] = useState(false);
  const [exportOptions, setExportOptions] = useState({
    verifiedOnly: true,
    includeSources: true,
    includeConfidence: true,
    includeAuditTrail: true
  });

  const handleExport = (format) => {
    try {
      if (format === 'excel') {
        const downloadPath = documents[0]?.downloads?.excel;
  
        if (!downloadPath) {
          addToast(
            'error',
            'Download Failed',
            'No Excel file is available. Process the document first.'
          );
          return;
        }
  
        const link = document.createElement('a');
        link.href = `http://127.0.0.1:8000${downloadPath}`;
        link.download = '';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
  
        addToast(
          'success',
          'Excel Downloaded',
          'Downloaded the Excel file generated by the backend.'
        );
  
      } else if (format === 'csv') {
        const downloadPath = documents[0]?.downloads?.csv;
  
        if (!downloadPath) {
          addToast(
            'error',
            'Download Failed',
            'No CSV file is available. Process the document first.'
          );
          return;
        }
  
        const link = document.createElement('a');
        link.href = `http://127.0.0.1:8000${downloadPath}`;
        link.download = '';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
  
        addToast(
          'success',
          'CSV Downloaded',
          'Downloaded the CSV generated by the backend.'
        );
  
      } else if (format === 'txt') {
        const downloadPath = documents[0]?.downloads?.txt;
  
        if (!downloadPath) {
          addToast(
            'error',
            'Download Failed',
            'No TXT file is available. Process the document first.'
          );
          return;
        }
  
        const link = document.createElement('a');
        link.href = `http://127.0.0.1:8000${downloadPath}`;
        link.download = '';
        document.body.appendChild(link);
        link.click();
        document.body.removeChild(link);
  
        addToast(
          'success',
          'TXT Downloaded',
          'Downloaded the TXT generated by the backend.'
        );
  
      } else if (format === 'json') {
        exportToJSON(documents, applicantName);
  
        addToast(
          'success',
          'JSON Payload Generated',
          'Downloaded structured JSON schema file.'
        );
  
      } else if (format === 'pdf') {
        exportToPDF(documents, applicantName);
  
        addToast(
          'success',
          'PDF Dossier Generated',
          'Generated printable KYC verification dossier.'
        );
      }
  
    } catch (err) {
      console.error(err);
  
      addToast(
        'error',
        'Export Error',
        'Failed to generate file.'
      );
    }
  };

  const handleExportAll = () => {
    handleExport('excel');
    setTimeout(() => handleExport('csv'), 400);

  setTimeout(() => handleExport('json'), 800);

  setTimeout(() => handleExport('pdf'), 1200);

  setTimeout(() => handleExport('txt'), 1600);
};

const sampleJsonSchema = JSON.stringify(
  documents.length > 0
    ? documents.reduce((acc, doc) => {
        acc[doc.name] = doc.extractedData || {};
        return acc;
      }, {})
    : {},
  null,
  2
);

  const handleCopyCode = () => {
    navigator.clipboard.writeText(sampleJsonSchema);
    setCopiedCode(true);
    setTimeout(() => setCopiedCode(false), 2500);
  };

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl font-bold text-slate-900 tracking-tight">Export Center</h1>
          <p className="text-xs text-slate-500 mt-1">
            Download your verified structured information across multiple enterprise formats or integrate via Webhooks.
          </p>
        </div>
        <button
          onClick={handleExportAll}
          className="inline-flex items-center gap-1.5 px-4 py-2 bg-indigo-600 hover:bg-indigo-700 text-white text-xs font-bold rounded-xl shadow-glow transition-all active:scale-95"
        >
          <Sparkles className="w-3.5 h-3.5" />
          <span>Export All Data Formats</span>
        </button>
      </div>

      {/* Pre-Export Readiness Summary Card */}
      <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-subtle flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <span className="text-[11px] font-bold text-slate-400 uppercase tracking-wider">
            Export Package Summary
          </span>
          <h3 className="text-sm font-bold text-slate-900 mt-0.5">
            Applicant: {applicantName} (#KYC-2026-84920)
          </h3>
          <p className="text-xs text-slate-500 mt-0.5">
            {totalDocuments} Documents • {verifiedFields} of {totalFields} Fields Verified • {averageConfidence}% Confidence
          </p>
        </div>

        <div className="flex items-center gap-3">
          <div className="px-3 py-1.5 rounded-xl bg-emerald-50 border border-emerald-200 text-emerald-800 text-xs font-bold flex items-center gap-1.5">
            <ShieldCheck className="w-4 h-4 text-emerald-600" />
            <span>Ready for Export</span>
          </div>
        </div>
      </div>

      {/* 4 Main Format Export Cards */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {/* Excel Card */}
        <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-subtle hover:border-emerald-300 hover:shadow-card transition-all flex flex-col justify-between space-y-4">
          <div>
            <div className="w-10 h-10 rounded-xl bg-emerald-50 text-emerald-600 flex items-center justify-center mb-3">
              <FileSpreadsheet className="w-5 h-5" />
            </div>
            <h3 className="text-sm font-bold text-slate-900">Microsoft Excel (.xlsx)</h3>
            <p className="text-xs text-slate-500 mt-1">
              Multi-sheet workbook containing Master Fields, Quality Index, and Reconciliation audit trail.
            </p>
          </div>
          <button
            onClick={() => handleExport('excel')}
            className="w-full py-2.5 px-3 bg-slate-900 hover:bg-slate-800 text-white rounded-xl text-xs font-semibold flex items-center justify-center gap-1.5 transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download Excel</span>
          </button>
        </div>

        {/* CSV Card */}
        <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-subtle hover:border-blue-300 hover:shadow-card transition-all flex flex-col justify-between space-y-4">
          <div>
            <div className="w-10 h-10 rounded-xl bg-blue-50 text-blue-600 flex items-center justify-center mb-3">
              <FileText className="w-5 h-5" />
            </div>
            <h3 className="text-sm font-bold text-slate-900">Delimited CSV (.csv)</h3>
            <p className="text-xs text-slate-500 mt-1">
              Flat standardized table for seamless import into PostgreSQL, Snowflake, or CRM pipelines.
            </p>
          </div>
          <button
            onClick={() => handleExport('csv')}
            className="w-full py-2.5 px-3 bg-slate-900 hover:bg-slate-800 text-white rounded-xl text-xs font-semibold flex items-center justify-center gap-1.5 transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download CSV</span>
          </button>
        </div>

        {/* JSON Schema Card */}
        <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-subtle hover:border-indigo-300 hover:shadow-card transition-all flex flex-col justify-between space-y-4">
          <div>
            <div className="w-10 h-10 rounded-xl bg-indigo-50 text-indigo-600 flex items-center justify-center mb-3">
              <Code className="w-5 h-5" />
            </div>
            <h3 className="text-sm font-bold text-slate-900">JSON Payload (.json)</h3>
            <p className="text-xs text-slate-500 mt-1">
              Full structured JSON schema including bounding coordinates, OCR tokens, and validation flags.
            </p>
          </div>
          <button
            onClick={() => handleExport('json')}
            className="w-full py-2.5 px-3 bg-slate-900 hover:bg-slate-800 text-white rounded-xl text-xs font-semibold flex items-center justify-center gap-1.5 transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Download JSON</span>
          </button>
        </div>

        {/* PDF Dossier Card */}
        <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-subtle hover:border-rose-300 hover:shadow-card transition-all flex flex-col justify-between space-y-4">
          <div>
            <div className="w-10 h-10 rounded-xl bg-rose-50 text-rose-600 flex items-center justify-center mb-3">
              <FileCheck className="w-5 h-5" />
            </div>
            <h3 className="text-sm font-bold text-slate-900">Official PDF Dossier (.pdf)</h3>
            <p className="text-xs text-slate-500 mt-1">
              Formatted executive summary dossier with document breakdown, verification signatures, and timestamps.
            </p>
          </div>
          <button
            onClick={() => handleExport('pdf')}
            className="w-full py-2.5 px-3 bg-slate-900 hover:bg-slate-800 text-white rounded-xl text-xs font-semibold flex items-center justify-center gap-1.5 transition-colors"
          >
            <Download className="w-3.5 h-3.5" />
            <span>Generate PDF</span>
          </button>
        </div>
      </div>
      {/* TXT Card */}
      <div className="p-5 rounded-2xl bg-white border border-slate-200 shadow-subtle hover:border-slate-400 hover:shadow-card transition-all flex flex-col justify-between space-y-4">
        <div>
          <div className="w-10 h-10 rounded-xl bg-slate-100 text-slate-600 flex items-center justify-center mb-3">
            <FileText className="w-5 h-5" />
          </div>

          <h3 className="text-sm font-bold text-slate-900">
            Plain Text (.txt)
          </h3>

          <p className="text-xs text-slate-500 mt-1">
            Clean extracted document text for reading, editing, or archival.
          </p>
        </div>

        <button
          onClick={() => handleExport('txt')}
          className="w-full py-2.5 px-3 bg-slate-900 hover:bg-slate-800 text-white rounded-xl text-xs font-semibold flex items-center justify-center gap-1.5 transition-colors"
        >
          <Download className="w-3.5 h-3.5" />
          <span>Download TXT</span>
        </button>
      </div>
      {/* Enterprise Integration Snippet */}
      <div className="p-5 sm:p-6 rounded-2xl bg-white border border-slate-200 shadow-subtle space-y-3">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Database className="w-4 h-4 text-indigo-600" />
            <h3 className="text-xs font-bold text-slate-900 uppercase tracking-wider">
              Enterprise REST & Webhook Payload Preview
            </h3>
          </div>
          <button
            onClick={handleCopyCode}
            className="inline-flex items-center gap-1 text-xs text-indigo-600 hover:text-indigo-800 font-semibold transition-colors"
          >
            {copiedCode ? <Check className="w-3.5 h-3.5 text-emerald-600" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copiedCode ? 'Copied!' : 'Copy Schema'}</span>
          </button>
        </div>

        <div className="p-4 rounded-xl bg-slate-950 font-mono text-[11px] text-slate-300 overflow-x-auto border border-slate-800">
          <pre>{sampleJsonSchema}</pre>
        </div>
      </div>
    </div>
  );
};
